---
- name: gather hypervisor facts
  setup:
  delegate_to: "{{ hyper }}"

- name: group hypervisors by distro
  group_by: key=os_{{ ansible_distribution }}_{{ ansible_distribution_major_version }}
  delegate_to: "{{ hyper }}"

- name: set variables specific to CentOS 6
  set_fact:
    virt_install_cpu_model: "host"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
  delegate_to: "{{ hyper }}"

- name: set variables specific to CentOS 7
  set_fact:
    virt_install_cpu_model: "host-model"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  delegate_to: "{{ hyper }}"

- name: copy over kickstart file
  template: src="kickstart.cfg" dest="{{ kickstart_tempdir }}/{{ inventory_hostname }}.ks"
  sudo: yes
  delegate_to: "{{ hyper }}"

- name: copy over virt-install script
  template: src="virt-install.sh" dest="{{ kickstart_tempdir }}/{{ inventory_hostname }}-install.sh"
  sudo: yes
  delegate_to: "{{ hyper }}"

- name: run virt-install script
  command: "bash {{ kickstart_tempdir }}/{{ inventory_hostname }}-install.sh"
  sudo: yes
  environment: "{{ env_virt_install }}"
  args:
    creates: "/etc/libvirt/qemu/{{ inventory_hostname }}.xml"
  delegate_to: "{{ hyper }}"

- name: wait for VM to become available before continuing
  wait_for: port=22 host="{{ provisioning_wait_for_addr | default(inventory_hostname) }}" timeout=300
  delegate_to: "{{ bastion_host | default(hyper) }}"

- name: Remove kickstart file
  sudo: yes
  file: path="{{ kickstart_tempdir }}/{{ inventory_hostname }}.ks" state=absent
  delegate_to: "{{ hyper }}"

- name: Remove install script
  sudo: yes
  file: path="{{ kickstart_tempdir }}/{{ inventory_hostname }}-install.sh" state=absent
  delegate_to: "{{ hyper }}"
